default: &default
  adapter: postgresql
  encoding: unicode
  username: neilni
  host: localhost
  password:
  pool: 5

development:
  <<: *default
  database: companyserver_development

test:
  <<: *default
  database: companyserver_test

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host:     <%= ENV['RDS_HOSTNAME'] %>
  